package GUI;

import Negocio.Componentes.ArmCheioException;
import Negocio.ConfiguraFacil;
import java.awt.Component;
import java.awt.HeadlessException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.DefaultComboBoxModel;

/**
 * @author Jaime Leite, João Marques, Nuno Rei e Rafael Lourenço
 * @version 12-2018
 */
public class ActStock extends javax.swing.JFrame {
    private Component controllingFrame;
    private DefaultComboBoxModel cb = new DefaultComboBoxModel();
    private final ConfiguraFacil d;
    
    /**
     * Criação do estado da janela ActStock
     * @param f 
     */
    public ActStock(ConfiguraFacil f) {
        this.d = f;
        this.d.getSortComponentes().forEach((a)->{cb.addElement(a.getNome());});
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Papyrus", 0, 50)); // NOI18N
        jLabel1.setText("Atualizar Stock:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 420, 67));

        jComboBox1.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 24)); // NOI18N
        jComboBox1.setModel(cb);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 320, 70));

        jLabel2.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 24)); // NOI18N
        jLabel2.setText("Componente a atualizar:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 24)); // NOI18N
        jLabel3.setText("Quantidade:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, -1, -1));

        jButton1.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jButton1.setText("Atualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 560, 430, 170));

        jTextField2.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 24)); // NOI18N
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 220, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mec1.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, -40, 450, 670));

        jButton2.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 560, 270, 170));

        jLabel4.setFont(new java.awt.Font("Lucida Bright", 0, 36)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/All-White-Abstract-Backgrounds-www.wallpapersbrowse.com_.png"))); // NOI18N
        jLabel4.setText("Sair");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        
    }//GEN-LAST:event_jComboBox1ActionPerformed
    
    /**
     * Escolheu atualizar um certo componente
     * @param evt 
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            int q = Integer.parseInt(this.jTextField2.getText());
            if(q>0) {
                List<String> res = this.d.AddCompStock(this.jComboBox1.getSelectedItem().toString(),q);
                StringBuilder sb = new StringBuilder();
                res.forEach(s->{sb.append(s);sb.append("\n");});
                JOptionPane.showMessageDialog(this.controllingFrame,"Atualização bem sucedida!\nProduções realizadas:\n"
                    +sb.toString(),"INFORMAÇÃO",JOptionPane.INFORMATION_MESSAGE);
            }
            else
                JOptionPane.showMessageDialog(this.controllingFrame,"Insira uma quantidade positiva.",
                    "ERROR MESSAGE",JOptionPane.ERROR_MESSAGE);
        }
        catch(HeadlessException | NumberFormatException e){
            JOptionPane.showMessageDialog(this.controllingFrame,"Insira uma quantidade válida(só números inteiros).",
                "ERROR MESSAGE",JOptionPane.ERROR_MESSAGE);
        }
        catch(ArmCheioException e) {
            JOptionPane.showMessageDialog(this.controllingFrame,"Armazém cheio.","ERROR MESSAGE",JOptionPane.ERROR_MESSAGE);
        }
        finally {
            dispose();
            execActStock();
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * Escolheu fazer loggout
     * @param evt 
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JOptionPane.showMessageDialog(this.controllingFrame,"Loggout efetuado.","INFORMAÇÃO",JOptionPane.INFORMATION_MESSAGE);
        dispose();
        Login a = new Login(this.d);
        a.execLogin();
    }//GEN-LAST:event_jButton2ActionPerformed
   
    public void execActStock() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(()->{new ActStock(this.d).setVisible(true);});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}