package GUI;

import Negocio.Componentes.Componente;
import Negocio.ConfiguraFacil;
import Negocio.Configuracoes.Configuracao;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 * @author Jaime Leite, João Marques, Nuno Rei e Rafael Lourenço
 * @version 12-2018
 */
public class CriarConfGUI extends javax.swing.JFrame {
    private ConfiguraFacil d;
    private Configuracao auxC;
    private DefaultListModel model1;
    private DefaultListModel model2;
    private Component controllingFrame;
    private List<String> tipos;
    
    /**
     * Criação do estado da janela CriarConfGUI
     * @param f
     * @param con 
     */
    public CriarConfGUI(ConfiguraFacil f,Configuracao con) {
        this.d = f;
        this.auxC = con;
        this.tipos = new ArrayList<>();
        con.getComponentes().forEach((a)->{
            this.d.getComponentesEssenciais().stream().filter((p)->(p.getID().equals(a) && !this.tipos.contains(p.getTipo())))
                .forEachOrdered((p)->{
                    this.tipos.add(p.getTipo());
            });
         });
        this.model1 = new DefaultListModel();
        this.model2 = new DefaultListModel();
        this.d.getComponentesEssenciais().forEach((a)->{
            if(!this.auxC.getComponentes().contains(a.getID()))
                this.model1.addElement(a.getNome());
        });
        this.auxC.getComponentes().forEach((a)->{
            this.d.getComponentesEssenciais().stream().filter((p) -> (p.getID().equals(a))).forEachOrdered((p) -> {
                this.model2.addElement(p.getNome());
            });
         });
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Papyrus", 1, 50)); // NOI18N
        jLabel1.setText("Criar Configuração:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N
        jLabel2.setText("Selecione os Componentes Essencias para sua configuraçao:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jList1.setModel(model1);
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 560, 340));

        jLabel3.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 18)); // NOI18N
        jLabel3.setText("Todos os componentes Essenciais disponiveis:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 510, -1));

        jList2.setModel(model2);
        jScrollPane2.setViewportView(jList2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 250, 580, 340));

        jLabel4.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 18)); // NOI18N
        jLabel4.setText("Componentes Essenciais Selecionados:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 210, -1, -1));

        jButton1.setText("Escolher Pacote");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 650, 237, 90));

        jButton2.setText("Passo a Passo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 650, 216, 90));

        jButton3.setText("Sair");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 650, 100, 90));

        jLabel5.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 24)); // NOI18N
        jLabel5.setText("SUB TOTAL:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 90, -1, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 24)); // NOI18N
        jLabel6.setText("€");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 90, -1, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 24)); // NOI18N
        jLabel7.setText(String.valueOf(auxC.getPreco()));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 80, 250, 50));

        jLabel8.setFont(new java.awt.Font("Lucida Sans Typewriter", 2, 14)); // NOI18N
        jLabel8.setText("");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 610, 1250, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/black-and-white-desktop-wallpaper-hd-wallpaper-1000195.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 3210, 1700));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Escolhe configuração por pacotes
     * @param evt 
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(this.model2.getSize() == 5){
            dispose();
            PacotesGUI a = new PacotesGUI(this.d,this.auxC);
            a.execPacotesGUI();
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * Escolhe configuração passo a passo
     * @param evt 
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(this.model2.getSize()==5){
            dispose();
            PapGUI a = new PapGUI(this.d,this.auxC);
            a.execPapGUI();
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    
    /**
     * Escolhe um componente para adicionar
     * @param evt 
     */
    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        Componente aux = this.d.getComponenteNome(this.jList1.getSelectedValue());
        if(aux!=null) {
            this.jLabel8.setText(aux.getDescricao());
            if (evt.getClickCount()== 2 && this.model2.getSize()<=5){
                if(!this.tipos.contains(aux.getTipo())) {
                    this.auxC.addComponente(aux.getID(),aux.getPreco());
                    dispose();
                    execCriarConfGUI();
                }
                else {
                    Object[] options = {"SIM","NÃO"};
                    int result = JOptionPane.showOptionDialog(null, "Já existe um Componente do tipo "+aux.getTipo()+".\nDeseja troca-lo?"
                        ,"TIPOS IGUAIS",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE,null,options,null );
                    if (result == JOptionPane.YES_OPTION) {
                        this.auxC = this.d.remComp(this.auxC,aux.getTipo());
                        List<String> add = new ArrayList<>();
                        add.add(aux.getID());
                        this.auxC = this.d.addComponente(this.auxC,add);
                        dispose();
                        execCriarConfGUI();
                    }
                }
                
            }
        }
    }//GEN-LAST:event_jList1MouseClicked
    
    /**
     * Escolhe fazer loggout
     * @param evt 
     */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JOptionPane.showMessageDialog(this.controllingFrame,"Loggout efetuado","INFORMAÇÃO",JOptionPane.INFORMATION_MESSAGE);
        dispose();
        Login a = new Login(this.d);
        a.execLogin();
    }//GEN-LAST:event_jButton3ActionPerformed

    public void execCriarConfGUI() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriarConfGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(()->{new CriarConfGUI(d,auxC).setVisible(true);});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}